apiVersion: v1
kind: Service
metadata:
  name: peximet-seed
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    run: peximet-seed
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: peximet-seed
  name: peximet-seed
spec:
  serviceName: peximet-seed
  replicas: 2
  selector:
    matchLabels:
      run: peximet-seed
  template:
    metadata:
      labels:
        run: peximet-seed
    spec:
      containers:
      - name: peximet-seed
        image: ziyasal/peximet
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SEED_NODES
          value: peximet-seed-0.peximet-seed,peximet-seed-1.peximet-seed
        command: ["/bin/sh", "-c", "HOST_NAME=${POD_NAME}.peximet-seed java -jar /app/app.jar"]
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP

